In [143]:
import pandas as pd
import pandas_profiling
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.formula.api as smf
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE

In [2]:
df = pd.read_csv('D:/DS/analytics_edge/2. Linear Regression/climate_change.csv')

In [3]:
pandas_profiling.ProfileReport(df)

In [5]:
df.sample(5)

Year  Month    MEI     CO2      CH4      N2O   CFC-11   CFC-12  \
219  2001      8  0.367  369.63  1765.16  316.233  260.400  542.131   
259  2004     12  0.643  377.45  1797.24  318.825  252.754  542.172   
40   1986      9  1.166  345.01  1680.44  306.867  226.343  405.584   
161  1996     10 -0.387  359.54  1774.50  311.850  268.728  530.837   
226  2002      3 -0.201  373.93  1786.67  316.969  260.008  543.473   

           TSI  Aerosols   Temp  
219  1366.4475    0.0021  0.498  
259  1366.1552    0.0027  0.381  
40   1365.6034    0.0126  0.016  
161  1365.6315    0.0064  0.089  
226  1367.0065    0.0020  0.586

In [78]:
df['cfc_eleven'] = df['CFC-11']
df['cfc_twelve'] = df['CFC-12']

In [166]:
X = pd.DataFrame(df.loc[: , ['Year', 'Month', 'MEI', 'CO2', 'CH4', 'N2O', 'cfc_eleven', 'cfc_twelve', 'TSI', 'Aerosols']])

In [167]:
y = pd.DataFrame(df.Temp)

In [168]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [169]:
X_train_df = pd.DataFrame(X_train)
X_test_df = pd.DataFrame(X_test)
y_train_df = pd.DataFrame(y_train)
y_train_df = pd.DataFrame(y_train)

In [171]:
lm = smf.ols(formula = 'Temp ~ MEI+CO2+CH4+N2O+TSI+Aerosols+cfc_eleven+cfc_twelve', data = df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   Temp   R-squared:                       0.744
Model:                            OLS   Adj. R-squared:                  0.737
Method:                 Least Squares   F-statistic:                     108.6
Date:                Thu, 27 Jun 2019   Prob (F-statistic):           8.21e-84
Time:                        21:30:35   Log-Likelihood:                 303.02
No. Observations:                 308   AIC:                            -588.0
Df Residuals:                     299   BIC:                            -554.5
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -127.6958     19.191     -6.654      0.000    -165.462     -89.929
MEI            0.0663      0.006     10.722      0.000       0.054       0.078
CO2            0.0052      0.002      2.375      0.018       0.001       0.010
CH4         6.371e-05      0.000      0.128      0.898      -0.001       0.001
N2O           -0.0169      0.008     -2.161      0.032      -0.032      -0.002
TSI            0.0959      0.014      6.844      0.000       0.068       0.123
Aerosols      -1.5818      0.210     -7.535      0.000      -1.995      -1.169
cfc_eleven    -0.0073      0.001     -4.980      0.000      -0.010      -0.004
cfc_twelve     0.0043      0.001      4.875      0.000       0.003       0.006
==============================================================================
Omnibus:                        6.703   Durbin-Watson:                   0.978
Prob(Omnibus):                  0.035   Jarque-Bera (JB):                8.299
Skew:                           0.191   Prob(JB):                       0.0158
Kurtosis:                       3.708   Cond. No.                     8.58e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.58e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

Correlation Coefficients for N2O

In [172]:
np.corrcoef(df.N2O, df.MEI)

array([[ 1.        , -0.16237531],
       [-0.16237531,  1.        ]])

In [173]:
np.corrcoef(df.N2O, df.CH4)

array([[1.        , 0.89440921],
       [0.89440921, 1.        ]])

In [174]:
np.corrcoef(df.N2O, df.CO2)

array([[1.        , 0.98113544],
       [0.98113544, 1.        ]])

In [175]:
np.corrcoef(df.N2O, df.TSI)

array([[1.        , 0.03989183],
       [0.03989183, 1.        ]])

In [176]:
np.corrcoef(df.N2O, df.Aerosols)

array([[ 1.        , -0.35349882],
       [-0.35349882,  1.        ]])

In [177]:
np.corrcoef(df.N2O, df.cfc_eleven)

array([[1.        , 0.41215475],
       [0.41215475, 1.        ]])

In [178]:
np.corrcoef(df.N2O, df.cfc_twelve)

array([[1.        , 0.83929545],
       [0.83929545, 1.        ]])

Correlation Coefficients for CFC-11

In [179]:
np.corrcoef(df.cfc_eleven, df.MEI)

array([[1.        , 0.08817074],
       [0.08817074, 1.        ]])

In [180]:
np.corrcoef(df.cfc_eleven, df.CH4)

array([[1.        , 0.71350408],
       [0.71350408, 1.        ]])

In [181]:
np.corrcoef(df.cfc_eleven, df.CO2)

array([[1.        , 0.40128447],
       [0.40128447, 1.        ]])

In [182]:
np.corrcoef(df.cfc_eleven, df.TSI)

array([[1.        , 0.28462884],
       [0.28462884, 1.        ]])

In [183]:
np.corrcoef(df.cfc_eleven, df.Aerosols)

array([[ 1.        , -0.03230227],
       [-0.03230227,  1.        ]])

In [184]:
np.corrcoef(df.cfc_eleven, df.cfc_twelve)

array([[1.        , 0.83138131],
       [0.83138131, 1.        ]])

In [186]:
lm = smf.ols(formula = 'Temp ~ MEI+N2O+TSI+Aerosols', data = df).fit()
lm.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   Temp   R-squared:                       0.716
Model:                            OLS   Adj. R-squared:                  0.712
Method:                 Least Squares   F-statistic:                     191.1
Date:                Thu, 27 Jun 2019   Prob (F-statistic):           1.54e-81
Time:                        21:30:50   Log-Likelihood:                 287.11
No. Observations:                 308   AIC:                            -564.2
Df Residuals:                     303   BIC:                            -545.6
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -134.0831     18.952     -7.075      0.000    -171.378     -96.788
MEI            0.0701      0.006     11.146      0.000       0.058       0.082
N2O            0.0237      0.001     21.029      0.000       0.021       0.026
TSI            0.0929      0.014      6.691      0.000       0.066       0.120
Aerosols      -1.8164      0.215     -8.455      0.000      -2.239      -1.394
==============================================================================
Omnibus:                       10.054   Durbin-Watson:                   0.873
Prob(Omnibus):                  0.007   Jarque-Bera (JB):               15.352
Skew:                           0.208   Prob(JB):                     0.000464
Kurtosis:                       4.011   Cond. No.                     4.85e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.85e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

#### Step function in R will be implemented using the feature_selection function of sklearn

* sklearn.feature_selection.RFE


In [188]:
linreg = LinearRegression()
feature_selector = RFE(linreg, 5, step = 1)
feature_selector = feature_selector.fit(X_train, y_train)

C:\Users\Atheesh Krishnan\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [189]:
feature_selector.ranking_

array([4, 3, 1, 5, 6, 1, 1, 2, 1, 1])

In [190]:
feature_selector.support_

array([False, False,  True, False, False,  True,  True, False,  True,
        True])

In [195]:
feature_names = list(X_train_df.columns)

In [196]:
print("Features sorted by their rank:")
print(sorted(zip(map(lambda x: round(x, 4), feature_selector.ranking_), feature_names)))

Features sorted by their rank:
[(1, 'Aerosols'), (1, 'MEI'), (1, 'N2O'), (1, 'TSI'), (1, 'cfc_eleven'), (2, 'cfc_twelve'), (3, 'Month'), (4, 'Year'), (5, 'CO2'), (6, 'CH4')]


The rankings of the feature based on Recursive Feature Elimination is as above.

In [201]:
smf.ols(formula = 'Temp ~ Aerosols + MEI + N2O + TSI + cfc_twelve + cfc_eleven ', data = df).fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                   Temp   R-squared:                       0.739
Model:                            OLS   Adj. R-squared:                  0.734
Method:                 Least Squares   F-statistic:                     142.2
Date:                Thu, 27 Jun 2019   Prob (F-statistic):           9.32e-85
Time:                        21:32:47   Log-Likelihood:                 300.13
No. Observations:                 308   AIC:                            -586.3
Df Residuals:                     301   BIC:                            -560.2
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept   -125.1457     19.271     -6.494      0.000    -163.068     -87.223
Aerosols      -1.6431      0.209     -7.844      0.000      -2.055      -1.231
MEI            0.0671      0.006     10.855      0.000       0.055       0.079
N2O           -0.0052      0.006     -0.897      0.370      -0.016       0.006
TSI            0.0927      0.014      6.612      0.000       0.065       0.120
cfc_twelve     0.0044      0.001      5.150      0.000       0.003       0.006
cfc_eleven    -0.0074      0.001     -5.080      0.000      -0.010      -0.005
==============================================================================
Omnibus:                        6.138   Durbin-Watson:                   0.945
Prob(Omnibus):                  0.046   Jarque-Bera (JB):                8.254
Skew:                           0.126   Prob(JB):                       0.0161
Kurtosis:                       3.762   Cond. No.                     5.52e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 5.52e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [202]:
linreg = LinearRegression()
linreg.fit(X_train, y_train)
linreg.score(X_test, y_test)

0.7105026180603247

In [203]:
linreg.coef_.mean()

-0.1432047907271023

In [204]:
linreg.intercept_

array([-130.40941918])

In [205]:
y_pred = linreg.predict(X_test)

In [206]:
print(mean_absolute_error(y_test, y_pred))
print(mean_squared_error(y_test, y_pred))
print(np.sqrt(mean_squared_error(y_test, y_pred)))
print(r2_score(y_test, y_pred))

0.07393626391432144
0.008097773547310025
0.08998762996829078
0.7105026180603247
